### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [synacktiv/octoscan#7]
Could you please tag the source? This allows distributions to get the complete source from GitHub if they want. Remove the issue of dealing with commits for distributions.

Thanks

**Comment by fabaff** [comment]
Something like `git tag -a 0.x.0 && git push origin 0.x.0` will make it show up at https://github.com/synacktiv/octoscan/tags. Releases could then be created. To make the life of package maintainers easier, releases are often not really needed but users do often appreciate them.

**Comment by echoix** [comment]
On the GitHub interface, creating a release also creates a matching tag, so it's one step for both.

**Comment by fabaff** [comment]
@hugo-syn, thank you.
